### Send POST request with json body
POST localhost:9909/adduser
Content-Type: application/json

{
  "username": "sharifanani2",
  "password": "woahpassword2",
  "email": "sharif.anani2@bigevilcorp.com"
}

###